### ISSUE TITLE
Document environment setup and installation procedure

### ISSUE THREAD

**Issue by matthew-reynolds** [uwreact/frc_control#11]
# 🚀 Feature Request

See #7. We need **very thorough** documentation explaining how to setup the development environment ~and install code onto the roboRIO~(Note: rio instructions moved to #30).

**Comment by Matthew-Reynolds** [comment]
Thorough instructions for s

**Comment by matthew-reynolds** [comment]
Whoops

**Comment by matthew-reynolds** [comment]
Note that this should focus on 2019 now that the season has launched. See #23

**Comment by matthew-reynolds** [comment]
Environment setup instructions are fairly comprehensive, and were added with PR #31. Installing code on the rio is still WIP, but is a fairly distinct task. I'm going to break up these two issues. See #30
