### ISSUE TITLE
Publish match data, driver station mode

### ISSUE THREAD

**Issue by matthew-reynolds** [uwreact/frc_control#50]
# 🚀 Feature Request

Part of #13.

The primary function of the driver station is to mimic the commands the real driver station (and/or FMS) send to the robot, with the main application being gazebo simulation of the robot. We therefore want to publish at least:
 - Driver station mode (estop, disabled, teleop, autonomous, test)
 - is_ds_attached (For now, always true)
 - is_fms_attached (For now, always false)
 - Game-specific message (As with real DS, pulled from text box in app)
 - Alliance (Red, Blue, or Invalid. Pulled from dropdown in app; `Red 1`, `Red 2`, `Red 3`, `Blue 1`, `Blue 2`, `Blue 3`)
 - Location (Invalid, Left, Center, or Right. Bundled with above)
 - Match time

There are a couple of things that the driver station doesn't normally publish unless connected to the FMS. We want to be able to specify these, so they should likely live in an extra tab on our driver station, or in a popup window.
 - Event name
 - Match type (None, Practice, Quals, or Elims)
 - Match number
 - Replay number

This is dependant on having the ROS msgs specified, which will correspond closely with these fields.

**Comment by wmmc88** [comment]
Publish as in ros msg or publish as in however the driver station usually "publishes" the info

**Comment by matthew-reynolds** [comment]
As ROS messages. Good point, I wasn't clear about that.

In the real robot, we are able to read the data sent from the NI Driver Station and FMS. We take this data and publish it as ROS messages for the rest of the system to use.

In a simulated robot, we instead publish this data directly from the Driver Station to the ROS topics.
